# Copyright 2023 Intrinsic Innovation LLC

# proto-file: intrinsic/icon/hal/proto/hardware_module_config.proto
# proto-message: intrinsic_proto.icon.HardwareModuleConfig

name: "loopback_hardware_module"
module_config {
  [type.googleapis.com/intrinsic_proto.icon.LoopbackConfig] {
    cycle_duration: {
      seconds: 0
      nanos: 4000000
    }
  }
}
drives_realtime_clock: false
simulation_module_config {
  cycle_duration: {
    seconds: 0
    nanos: 4000000
  }
}

