# Copyright 2023 Intrinsic Innovation LLC

# Generic language utilities for golang.

load("//bazel:go_macros.bzl", "go_library")

go_library(
    name = "pointer",
    srcs = ["pointer.go"],
    visibility = ["//intrinsic:internal_api_users"],
)
