# Copyright 2023 Intrinsic Innovation LLC

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "realtime_annotations",
    hdrs = ["realtime_annotations.h"],
)

bzl_library(
    name = "cc_test_and_malloc_test_bzl",
    srcs = ["cc_test_and_malloc_test.bzl"],
)
